version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
