basePath: /api/
definitions:
  core.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: Swagger API for Golang Project.
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths:
  /users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.User'
      summary: Retrieves user based on given ID
swagger: "2.0"
